### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by meatballhat**
for compatibility with github/linguist

### CODE REVIEW

**Comment by crucialfelix** [comment]
Thanks for the PR. 

I'm not entirely sure that it needs to be or should be GPL.

This same grammar is in atom-supercollider and the license there is the more permissive MIT one:  https://github.com/crucialfelix/atom-supercollider/blob/master/LICENSE.md

So if anything I think it should follow that.  This is the same license that all other grammars are using. They don't use the same license as the language.

btw. I did try to get in linguist previously but didn't get around to submitting a code sample. I assume that they asked that the grammar include a license as well. Thanks for doing this !

**Comment by meatballhat** [comment]
@crucialfelix makes perfect sense to me!  I'll gladly switch to MIT in `LICENSE.md`.  I hadn't gotten around to submitting a PR to linguist yet, as the tests were failing due to the lack of a license.  :soon:

**Comment by meatballhat** [comment]
Tested via `licensee`:

``` bash
$ licensee
License file: LICENSE.md
Attribution: Copyright (c) 2014-2015 Chris Sattinger
License: MIT License
Confidence: 100%
Method: Licensee::Matchers::Exact
```

**Comment by meatballhat** [comment]
@crucialfelix Yay thanks! :heart:

**Comment by crucialfelix** [comment]
Splendid, thanks a lot !  Its so annoying that Scala gets all the credit for our code :) Will be nice to get .sc / .scd support

I should also probably use this repo as a submodule in atom-supercollider. There is at least one fix over in that version that isn't here.  

```
Array[slot] : ArrayedCollection {
```

**Comment by meatballhat** [comment]
:+1: right on! :bear: :de: :fist:

**Comment by crucialfelix** [comment]
schland !  ah I see you are a Travis person. wir lieben euch !

**Comment by meatballhat** [comment]
:heart: :heart: :heart: I love that we get to support SuperCollider!

**Pull request merged**
